### ISSUE TITLE
Hot reload環境を整える

### ISSUE THREAD

**Issue by jackale** [jackale/elm-todomvc#4]
Elm liveというのが良さそう。

いったんelm reactorで賄えないかやってみる
-> reactorはホットリロードついてないのでやめた

https://github.com/wking-io/elm-live

**Comment by jackale** [comment]
```sh
[~/study/elm-todomvc][master]
ζ*ヮ)ζ < elm-live src/Main.elm --open --hot -- --output=build/main.js
elm-live:
  Hot Reloading is ON

  Warning: Hot Reloading does not replay the messages of the app.
  It just restores the previous state and can lead to bad state.
  If this happen, reload the app in the browser manually to fix it.

events.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:265:10)
    at Object.createServer (http.js:34:10)
    at model (/Users/kazutaka/.nodebrew/node/v8.9.4/lib/node_modules/elm-live/lib/src/start.js:259:75)
    at /Users/kazutaka/.nodebrew/node/v8.9.4/lib/node_modules/elm-live/node_modules/crocks/core/compose.js:8:14
    at settle (/Users/kazutaka/.nodebrew/node/v8.9.4/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:151:16)
    at /Users/kazutaka/.nodebrew/node/v8.9.4/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:27:62
    at fork (/Users/kazutaka/.nodebrew/node/v8.9.4/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:155:20)
    at /Users/kazutaka/.nodebrew/node/v8.9.4/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:224:16
```

nodeのバージョンが`v8.9.4`だったので古いっぽい
v10が対応してるっぽいけど12がactive ltsなのでとりあえず12入れてみよう
https://nodejs.org/ja/about/releases/

**Comment by jackale** [comment]
node v12で動作したので完了
